.TH MYSTRCAT 3 "September 2026" "libmyutils" "Library Functions"

.SH NAME
mystrcat \- concatenate two strings

.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.sp
.B int mystrcat(char *dest, const char *src);

.SH DESCRIPTION
The
.B mystrcat
function appends the string pointed to by
.B src
to the end of the string pointed to by
.B dest
and adds a terminating null character.

.SH AUTHOR
LAIBA
