.TH MYSTRNCPY 3 "September 2026" "libmyutils" "Library Functions"

.SH NAME
mystrncpy \- copy a limited number of characters

.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.sp
.B int mystrncpy(char *dest, const char *src, int n);

.SH DESCRIPTION
The
.B mystrncpy
function copies up to
.B n
characters from the string pointed to by
.B src
to the character array pointed to by
.B dest.

.SH AUTHOR
LAIBA
