.TH MYSTRLEN 3 "September 2026" "libmyutils" "Library Functions"

.SH NAME
mystrlen \- calculate the length of a string

.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.sp
.B int mystrlen(const char *s);

.SH DESCRIPTION
The
.B mystrlen
function calculates the number of characters in the string
.B s
before the terminating null character.

.SH AUTHOR
LAIBA 
