.TH MYSTRCPY 3 "September 2026" "libmyutils" "Library Functions"

.SH NAME
mystrcpy \- copy a string to another string

.SH SYNOPSIS
.B #include "../include/mystrfunctions.h"
.sp
.B int mystrcpy(char *dest, const char *src);

.SH DESCRIPTION
The
.B mystrcpy
function copies the string pointed to by
.B src
into the character array pointed to by
.B dest
including the terminating null character.

.SH AUTHOR
LAIBA
